Hunter entity introduced
PA165-MushroomHunter/MushroomHunter pull request #24
Opened 2017-10-18 20:43 UTC by Buvko

Hunter entity introduced
+ learning to work with forks and pull requests
+ fixed issue with two persistence modules

2017-10-20 20:27 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> + * Created by Matúš on 18.10.2017.
Use your github account name here

2017-10-20 20:33 UTC, bkompis requested changes
Good first draft, some renames should be made. Based on the team decision, we might want to add one more attribute (isAdmin flag) to the entity.

2017-10-20 20:33 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> +public class Hunter {
I'd call the entity 'MushroomHunter', to match the issue and diagrams.

2017-10-20 20:33 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> +    private String surName;
surName should be surname (it's one word)

2017-10-20 20:33 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> +    public String getSurName() {
rename to match the attribute

2017-10-20 20:33 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> +    public void setSurName(String surName) {
rename to match the attribute

2017-10-20 20:33 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/Hunter.java
> +}
If we want to add an 'admin' to the system, the simplest way would be to add a boolean flag to this entity (isAdmin), which can be used further.

2017-10-23 08:26 UTC, bkompis approved these changes
All fixed, I approve.

2017-10-23 08:27 UTC, merged

2017-10-24 16:40 UTC, bencikpeter commented
Minor detail, 
` @NotNull
    @Column(nullable=false,unique=true)
    private String firstName;`

I believe first name should not be unique...