proper javadoc added + name and surname are no longer unique
PA165-MushroomHunter/MushroomHunter pull request #32
Opened 2017-10-26 18:42 UTC by Buvko

2017-10-27 16:54 UTC, bencikpeter approved these changes
I'd say good. Those @NotNull and @Column(nullable=false) could stay imho, but no harm in removing them

2017-10-27 16:54 UTC, bencikpeter commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/MushroomHunter.java
> -    @NotNull
My opinion is that @NotNull could stay, just unique was problematic. You probably want a hunter to have a name set

2017-10-28 07:45 UTC, bkompis requested changes

2017-10-28 07:45 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/MushroomHunter.java
> -    @NotNull
I'd leave names not null, even though they are not unique

2017-10-28 07:45 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/MushroomHunter.java
> -    @NotNull
I'd leave names not null

2017-10-28 07:45 UTC, bkompis commented on persistence/target/classes/META-INF/persistence.xml
> -</persistence>
Why is this deleted?

2017-10-28 10:41 UTC, Buvko commented
NotNull on name and surname attribures re-added

2017-10-28 11:10 UTC, Buvko commented
column annotations added visits set added

2017-10-28 11:12 UTC, bkompis requested changes
Fix the star import, otherwise good

2017-10-28 11:12 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/MushroomHunter.java
> +    public void setVisits(Set<Visit> visits) {
this may be redundant, but no problem

2017-10-28 11:12 UTC, bkompis commented on persistence/src/main/java/cz/muni/fi/pa165/mushrooms/entity/MushroomHunter.java
> +import javax.persistence.*;
fix this import

2017-10-28 11:22 UTC, bkompis approved these changes

2017-10-28 11:22 UTC, merged